# Generated by Django 4.0.1 on 2023-03-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('img', models.ImageField(blank=True, upload_to='partfolio/%Y/%m/%d')),
                ('desc', models.TextField(max_length=500)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('upload', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio', to='about.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='about_categ_name_9aa225_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['id', 'slug'], name='about_folio_id_90e322_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['name'], name='about_folio_name_f54abd_idx'),
        ),
        migrations.AddIndex(
            model_name='folio',
            index=models.Index(fields=['-created'], name='about_folio_created_776224_idx'),
        ),
    ]
