# Generated by Django 4.1.7 on 2023-03-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=222)),
                ('desc', models.CharField(blank=True, max_length=222)),
                ('name', models.CharField(blank=True, max_length=222)),
                ('degree', models.CharField(blank=True, max_length=222)),
                ('phone', models.CharField(blank=True, max_length=222)),
                ('address', models.CharField(blank=True, max_length=222)),
                ('birthday', models.CharField(blank=True, max_length=222)),
                ('experience', models.CharField(blank=True, max_length=222)),
                ('email', models.CharField(blank=True, max_length=222)),
                ('freelance', models.CharField(blank=True, max_length=222)),
            ],
        ),
    ]
