# Generated by Django 4.0.1 on 2023-03-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_delete_me_gallery_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='url',
            new_name='urr',
        ),
    ]
